### PR TITLE
Fix arg_get builtin

### LINKED ISSUE #388: `args` library does not handle argument position correctly
```rust
// test.jk
println(Args.at(1))
```
```sh
> cargo run -- test.jk some_arg
some_other_arg
```

Expected behavior
```sh
> cargo run -- test.jk some_arg some_other_arg
some_arg
```

### PR DESCRIPTION
**Pull request by Skallwar**
Fixes #388

### CODE REVIEW

File: src/builtins.rs [hunk 1]
```diff
@@ -89,10 +89,15 @@ fn arg_get(ctx: &mut Context, args: Args) -> Option<ObjectInstance> {
     let args = ctx.args();
 
     // FIXME: Is this cast valid?
-    let result_string = args
-        .get(idx as usize)
-        .map(|s| s.to_owned())
-        .unwrap_or_default();
+    let result_string = match idx {
+        0 => ctx.path().map_or(std::env::args().nth(0).unwrap(), |s| {
```
Comment (CohenArthur) [inline src/builtins.rs:93]: I agree with clippy :D 
```suggestion
        0 => ctx.path().map_or(std::env::args().next().unwrap(), |s| {
```

**Review by CohenArthur — COMMENTED** [review]
Other than the clippy suggestion, this is perfect. You need to fix the functional tests as they are based on the bugged behavior. Could you also add one test for this new behavior? Thanks!

File: src/builtins.rs (hunk 1 above)
Comment (Skallwar) [reply src/builtins.rs]: Fixed, thanks
