### PR TITLE
Fix relationship between `Kind::Binding` and `Kind::TypedValue`

### LINKED ISSUE #661: Specify the exact relationship between `Kind::TypedValue` and `Kind::Binding`
Which one is the actual "place"/"lvalue" one? Which one is a reference to the other?

### PR DESCRIPTION
**Pull request by CohenArthur**
Fixes #661 

Can we actually remove `ValueRef`/`TypedValue`? I don't think we need it, since we should just be able to keep a `RefIdx` of a binding.

- [x] Fix missing typing of bindings 
- [x] Fix missing type-checking of bindings

### CODE REVIEW

File: fir/src/lib.rs [hunk 1]
```diff
@@ -203,7 +199,23 @@ pub enum Kind {
...
+        // /* or */
+        //
+        // foo(a: int)
+        //     ^^^^^^
+        //
+        // is that true?
+        // TODO: Add a `ty` field
+        // TODO: Should this be Option<RefIdx> actually? A binding can exist without a value,
+        // e.g. an argument in a function *is* a binding but does not have a value until runtime?
+        // FIXME: This should definitely be a Option<RefIdx>
```
Comment (CohenArthur) [inline fir/src/lib.rs:216]: this needs cleaning up and needs documentation

File: fir/src/lib.rs [hunk 2]
```diff
@@ -203,7 +199,23 @@ pub enum Kind {
...
+        to: Option<RefIdx>, // to Kind::{TypedValue, Instantiation, any expr?},
+        ty: Option<RefIdx>,
```
Comment (CohenArthur) [inline fir/src/lib.rs:218]: missing comment?

File: fir/src/lib.rs [hunk 3]
```diff
@@ -234,6 +246,13 @@ pub enum Kind {
     },
     Statements(Vec<RefIdx>), // to any kind
     Return(Option<RefIdx>),  // to any kind
+    // TODO: Rework this into a ValueReference or something?
+    // TODO: Does this need a `ty` field?
+    // TODO: Can we actually remove ValueRef entirely? since we can just have a RefIdx(Binding) - no, we can't
```
Comment (CohenArthur) [inline fir/src/lib.rs:251]: Cleanup

File: fire/src/lib.rs [hunk 4]
```diff
@@ -333,9 +284,9 @@ impl<'ast, 'fir> Fire<'ast, 'fir> {
                 args,
                 .. /* FIXME: Generics should be empty at this point */
             } => self.fire_call( node, to, args),
-            Kind::Binding { to } => self.fire_binding( node, to),
-            Kind::TypedValue { value, ty } => self.fire_typed_value( node, value, ty),
-            Kind::Return(expr) => self.fire_return( node, expr),
+            Kind::Binding { to, .. } => self.fire_binding(node, to),
+            Kind::NodeRef(to) => { self.fire_node_ref(to)?; self.gc.transfer(to, node.origin); KeepGoing },
```
Comment (CohenArthur) [inline fire/src/lib.rs:288]: it would be nice if this was cleaned up in a function

File: flatten/src/lib.rs [hunk 5]
```diff
@@ -774,10 +771,15 @@ impl<'ast> Ctx<'ast> {
 
         let data = FlattenData {
             scope: ctx.scope,
-            ast,
+            ast: dbg!(ast),
```
Comment (CohenArthur) [inline flatten/src/lib.rs:774]: Remove this

File: flatten/src/lib.rs [hunk 6]
```diff
@@ -774,10 +771,15 @@ impl<'ast> Ctx<'ast> {
...
         };
 
-        let kind = Kind::Binding { to: to_bind };
+        // FIXME: If there is a given type, we need to handle it here
```
Comment (CohenArthur) [inline flatten/src/lib.rs:777]: Open an issue about this

File: name_resolve/src/scoper.rs [hunk 7]
```diff
@@ -45,6 +45,7 @@ impl Scoper {
     }
 }
 
+// FIXME: This can be replaced by a TreeLike
```
Comment (CohenArthur) [inline name_resolve/src/scoper.rs:48]: Create an issue for this

File: recursive_typecheck/src/lib.rs [hunk 8]
```diff
@@ -154,19 +154,18 @@ impl Mapper<FlattenData<'_>, TypeData, Error> for TypeCtx {
...
+    //     data: FlattenData,
+    //     origin: OriginIdx,
+    //     to: RefIdx,
+    // ) -> Result<Node<TypeData>, Error> {
+    // Ok(Node {
+    //     data: TypeData::from(data).uses(ty),
+    //     origin,
+    //     kind: Kind::NodeRef(to),
+    // })
+    // }
```
Comment (CohenArthur) [inline recursive_typecheck/src/lib.rs:168]: dead code

File: typecheck/src/typer.rs [hunk 9]
```diff
@@ -206,6 +205,7 @@ impl<'ast, 'ctx> Mapper<FlattenData<'ast>, FlattenData<'ast>, Error> for Typer<'
             fir::Kind::Generic { .. } | fir::Kind::TypeOffset { .. } | fir::Kind::Loop { .. } => {
                 Ok(node)
             }
+            fir::Kind::Binding { to: None, ty: None } => unreachable!(),
```
Comment (CohenArthur) [inline typecheck/src/typer.rs:208]: Add a comment here

File: typecheck/src/typer.rs [hunk 10]
```diff
@@ -182,12 +182,11 @@ impl<'ast, 'ctx> Mapper<FlattenData<'ast>, FlattenData<'ast>, Error> for Typer<'
...
-            | fir::Kind::TypedValue {
-                ty: RefIdx::Unresolved,
-                value: ty,
-            }
-            | fir::Kind::Binding { to: ty }
-            | fir::Kind::TypedValue { ty, .. }
+            // if we have something to bind to, and there is no given type, then our binding is of this type - otherwise, trust the type
+            | fir::Kind::Binding { to: Some(ty), .. }
+            | fir::Kind::Binding { ty: Some(ty), .. }
+            // FIXME: Is that correct? how do we deal with marker types vs bindings?
```
Comment (CohenArthur) [inline typecheck/src/typer.rs:188]: this comment can be removed
